# Generated by Django 4.2.10 on 2024-06-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='usersitejunction',
            name='site',
        ),
        migrations.RemoveField(
            model_name='usersitejunction',
            name='user',
        ),
        migrations.AlterField(
            model_name='accommodationlisting',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='UserSiteJunction',
        ),
    ]
