# Generated by Django 4.2.10 on 2024-06-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_accommodationlisting_accomodation_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationlisting',
            old_name='accomodation_gallery',
            new_name='accommodation_gallery',
        ),
    ]
