# Generated by Django 4.2.10 on 2024-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_site_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('ZAR', 'South African Rand')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('ZAR', 'South African Rand')], max_length=3),
        ),
    ]
